# Generated by Django 5.0.6 on 2026-08-02 11:21

import django.db.models.deletion
import django.utils.timezone
import integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الموقع")),
                (
                    "url",
                    models.URLField(blank=True, default="", verbose_name="رابط الموقع"),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("store", "متجر إلكتروني"),
                            ("blog", "مدونة"),
                            ("saas", "نظام/SaaS"),
                            ("landing", "موقع تعريفي"),
                            ("other", "أخرى"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0f9b73", max_length=9, verbose_name="لون مميّز"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        default=integrations.models.generate_api_key,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="مفتاح API",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "موقع مرتبط",
                "verbose_name_plural": "المواقع المرتبطة",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitors",
                    models.PositiveIntegerField(default=0, verbose_name="الزيارات"),
                ),
                (
                    "sessions",
                    models.PositiveIntegerField(default=0, verbose_name="الجلسات"),
                ),
                (
                    "new_users",
                    models.PositiveIntegerField(default=0, verbose_name="مستخدمون جدد"),
                ),
                (
                    "orders",
                    models.PositiveIntegerField(default=0, verbose_name="الطلبات"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الإيرادات",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("up", "يعمل"),
                            ("down", "متوقّف"),
                            ("degraded", "بطيء"),
                        ],
                        default="up",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "response_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="زمن الاستجابة (ms)"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="وقت التسجيل"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="integrations.externalsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "لقطة إحصائية",
                "verbose_name_plural": "اللقطات الإحصائية",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
