# Generated by Django 5.0.6 on 2026-08-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="الاسم")),
                ("email", models.EmailField(max_length=254, verbose_name="البريد")),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "رسالة تواصل",
                "verbose_name_plural": "رسائل التواصل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(default="١", max_length=4, verbose_name="الرقم"),
                ),
                ("title", models.CharField(max_length=60, verbose_name="العنوان")),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "خطوة عمل",
                "verbose_name_plural": "خطوات العمل",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="العنوان")),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "emoji",
                    models.CharField(default="🌐", max_length=8, verbose_name="الرمز"),
                ),
                (
                    "gradient",
                    models.CharField(
                        blank=True,
                        choices=[("", "أخضر"), ("alt", "ذهبي"), ("alt2", "فيروزي")],
                        default="",
                        max_length=8,
                        verbose_name="التدرّج",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="الوسوم (مفصولة بفاصلة)",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, default="", verbose_name="الرابط"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
            ],
            options={
                "verbose_name": "مشروع",
                "verbose_name_plural": "المشاريع",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🌐", max_length=8, verbose_name="الأيقونة (إيموجي)"
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="العنوان")),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
            ],
            options={
                "verbose_name": "خدمة",
                "verbose_name_plural": "الخدمات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="تكنو شام", max_length=80, verbose_name="اسم العلامة"
                    ),
                ),
                (
                    "color_primary",
                    models.CharField(
                        default="#0f9b73", max_length=9, verbose_name="اللون الأساسي"
                    ),
                ),
                (
                    "color_primary_2",
                    models.CharField(
                        default="#16b98a", max_length=9, verbose_name="الأساسي الفاتح"
                    ),
                ),
                (
                    "color_deep",
                    models.CharField(
                        default="#0a3b2c", max_length=9, verbose_name="اللون الغامق"
                    ),
                ),
                (
                    "color_gold",
                    models.CharField(
                        default="#d8a43f", max_length=9, verbose_name="لون التمييز"
                    ),
                ),
                (
                    "color_paper",
                    models.CharField(
                        default="#f5f2ea", max_length=9, verbose_name="لون الخلفية"
                    ),
                ),
                (
                    "color_ink",
                    models.CharField(
                        default="#16211d", max_length=9, verbose_name="لون النص"
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        choices=[
                            ("Cairo", "Cairo"),
                            ("Tajawal", "Tajawal"),
                            ("Almarai", "Almarai"),
                            ("IBM Plex Sans Arabic", "IBM Plex Sans Arabic"),
                            ("Rubik", "Rubik"),
                        ],
                        default="Cairo",
                        max_length=40,
                        verbose_name="الخط",
                    ),
                ),
                (
                    "base_font_size",
                    models.PositiveSmallIntegerField(
                        default=16, verbose_name="حجم الخط الأساسي (px)"
                    ),
                ),
                (
                    "radius",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="استدارة الحواف (px)"
                    ),
                ),
                (
                    "dark_mode",
                    models.BooleanField(default=False, verbose_name="الوضع الداكن"),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="نصمّم ونبرمج مواقع",
                        max_length=160,
                        verbose_name="عنوان الواجهة",
                    ),
                ),
                (
                    "hero_highlight",
                    models.CharField(
                        default="تُبهر عملاءك",
                        max_length=80,
                        verbose_name="الكلمة المميّزة",
                    ),
                ),
                (
                    "hero_title_end",
                    models.CharField(
                        default="من أول نظرة.",
                        max_length=80,
                        verbose_name="تكملة العنوان",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="استوديو تكنو شام يحوّل أفكارك إلى تجارب رقمية بسيطة وأنيقة — أي موقع تحتاجه، بذوقٍ عالٍ وأداءٍ لا يخذلك.",
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        blank=True, default="", verbose_name="نبذة من نحن"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        default="9665XXXXXXXX",
                        max_length=40,
                        verbose_name="واتساب",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="info@technosham.com",
                        max_length=254,
                        verbose_name="البريد",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="+9665XXXXXXXX",
                        max_length=40,
                        verbose_name="الهاتف",
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True,
                        default="https://github.com/technosham",
                        verbose_name="GitHub",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        default="https://linkedin.com/in/technosham",
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "x_url",
                    models.URLField(
                        blank=True, default="https://x.com/technosham", verbose_name="X"
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        default="https://instagram.com/technosham",
                        verbose_name="Instagram",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=60, verbose_name="التسمية")),
                (
                    "value",
                    models.PositiveIntegerField(default=0, verbose_name="القيمة"),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, default="+", max_length=6, verbose_name="لاحقة"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "إحصائية",
                "verbose_name_plural": "الإحصائيات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="الاسم")),
                (
                    "role",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="الصفة"
                    ),
                ),
                ("quote", models.TextField(verbose_name="الرأي")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=5, verbose_name="التقييم"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
            ],
            options={
                "verbose_name": "رأي عميل",
                "verbose_name_plural": "آراء العملاء",
                "ordering": ["order", "id"],
            },
        ),
    ]
